// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://akofewiugtsviauyvkkz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFrb2Zld2l1Z3RzdmlhdXl2a2t6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM2MDA2NTgsImV4cCI6MjA4OTE3NjY1OH0.v87O4w0O1uW3DnBJybsZSDV1vQFS938tdrBrGLGjfD4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});